# -*- coding: utf-8 -*-
"""slurm.sh

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1i3QjIleVjEvcZM52ookxjiKw8DAag-Az
"""

#!/bin/bash
#SBATCH --job-name=shaivika_CIFAR
#SBATCH --mail-type=All
#SBATCH --mail-user=shaivika.anand@uqconnect.edu.au
#SBATCH --partition=vgpu
#SBATCH --gres=gpu:1

python ~/pattern_/task2.py